### ISSUE TITLE
Successfully edits comments but doesn't delete

### ISSUE THREAD

**Issue by seantcanavan** [chovy/reddit-eraser#2]
I just ran the tool locally but wasn't completely successful. It successfully edited my comments but didn't delete them afterwards.

I added an app on reddit and got the app key and secret and successfully ran the tool with them. Log output showed:

{"level":"info","message":"Starting with 1 concurrency","timestamp":"2017-02-07T20:42:06.878Z"}
{"level":"info","message":"erased comment name: IDENTIFIER","timestamp":"2017-02-07T20:42:11.955Z"}
{"level":"info","message":"deleted comment id: IDENTIFIER","timestamp":"2017-02-07T20:42:13.251Z"}
{"level":"info","message":"erased comment name: IDENTIFIER","timestamp":"2017-02-07T20:42:13.936Z"}
{"level":"info","message":"deleted comment id: IDENTIFIER","timestamp":"2017-02-07T20:42:15.205Z"}
{"level":"info","message":"erased comment name: IDENTIFIER","timestamp":"2017-02-07T20:42:15.799Z"}

**Comment by ralyodio** [comment]
hmm....you have to re-run it to get all comments deleted. I think it only does 10 at a time.

also i think if you're logged in you can still see your deleted comments. Try incognito code.

**Comment by seantcanavan** [comment]
There were many more than 10 log entries in the run.log file specifically say that "deleted comment id". Any ideas?

**Comment by ralyodio** [comment]
try now. it works -- guess they changed their api. 

You have to re-run a few times if you have a lot of comments and it can take a few minutes for their caches to clear.

**Comment by seantcanavan** [comment]
I just made a test account and comment and can confirm it worked.
